// Mock data — replace with real API calls later
export const facilities = [
  {
    id: 'us',
    name: 'US Facility',
    flag: 'us',
    lanes: [
      {
        id: 1,
        name: 'Lane 1',
        type: 'Batting',
        devices: [
          { name: 'Bowling Machine', icon: 'zap', status: 'online' },
          { name: 'CV Left Cam', icon: 'camera', status: 'online' },
          { name: 'CV Right Cam', icon: 'camera', status: 'offline' },
          { name: 'Display', icon: 'monitor', status: 'online' },
          { name: 'App', icon: 'smartphone', status: 'online' },
          { name: 'Tablets', icon: 'tablet', status: 'online' },
          { name: 'BM Tabs', icon: 'layout-grid', status: 'online' },
          { name: 'Server', icon: 'server', status: 'online' },
        ],
      },
      {
        id: 2,
        name: 'Lane 2',
        type: 'Batting',
        devices: [
          { name: 'Bowling Machine', icon: 'zap', status: 'online' },
          { name: 'CV Left Cam', icon: 'camera', status: 'online' },
          { name: 'CV Right Cam', icon: 'camera', status: 'online' },
          { name: 'Display', icon: 'monitor', status: 'online' },
          { name: 'App', icon: 'smartphone', status: 'online' },
          { name: 'Tablets', icon: 'tablet', status: 'online' },
          { name: 'BM Tabs', icon: 'layout-grid', status: 'online' },
          { name: 'Server', icon: 'server', status: 'online' },
        ],
      },
      {
        id: 3,
        name: 'Lane 3',
        type: 'Batting',
        devices: [
          { name: 'Bowling Machine', icon: 'zap', status: 'online' },
          { name: 'CV Left Cam', icon: 'camera', status: 'online' },
          { name: 'CV Right Cam', icon: 'camera', status: 'online' },
          { name: 'Display', icon: 'monitor', status: 'online' },
          { name: 'App', icon: 'smartphone', status: 'online' },
          { name: 'Tablets', icon: 'tablet', status: 'warning' },
          { name: 'BM Tabs', icon: 'layout-grid', status: 'online' },
          { name: 'Server', icon: 'server', status: 'online' },
        ],
      },
      {
        id: 4,
        name: 'Lane 4',
        type: 'Batting',
        devices: [
          { name: 'Bowling Machine', icon: 'zap', status: 'online' },
          { name: 'CV Left Cam', icon: 'camera', status: 'online' },
          { name: 'CV Right Cam', icon: 'camera', status: 'online' },
          { name: 'Display', icon: 'monitor', status: 'online' },
          { name: 'App', icon: 'smartphone', status: 'online' },
          { name: 'Tablets', icon: 'tablet', status: 'online' },
          { name: 'BM Tabs', icon: 'layout-grid', status: 'online' },
          { name: 'Server', icon: 'server', status: 'online' },
        ],
      },
      {
        id: 5,
        name: 'Lane 5',
        type: 'Batting',
        devices: [
          { name: 'Bowling Machine', icon: 'zap', status: 'offline' },
          { name: 'CV Left Cam', icon: 'camera', status: 'online' },
          { name: 'CV Right Cam', icon: 'camera', status: 'online' },
          { name: 'Display', icon: 'monitor', status: 'online' },
          { name: 'App', icon: 'smartphone', status: 'online' },
          { name: 'Tablets', icon: 'tablet', status: 'online' },
          { name: 'BM Tabs', icon: 'layout-grid', status: 'online' },
          { name: 'Server', icon: 'server', status: 'warning' },
        ],
      },
      {
        id: 6,
        name: 'Lane 6',
        type: 'Hybrid',
        devices: [
          { name: 'Bowling Machine', icon: 'zap', status: 'online' },
          { name: 'CV Left Cam', icon: 'camera', status: 'online' },
          { name: 'CV Right Cam', icon: 'camera', status: 'online' },
          { name: 'Display', icon: 'monitor', status: 'online' },
          { name: 'App', icon: 'smartphone', status: 'online' },
          { name: 'Tablets', icon: 'tablet', status: 'online' },
          { name: 'BM Tabs', icon: 'layout-grid', status: 'online' },
          { name: 'Server', icon: 'server', status: 'online' },
        ],
      },
      {
        id: 7,
        name: 'Lane 7',
        type: 'Hybrid',
        devices: [
          { name: 'Bowling Machine', icon: 'zap', status: 'online' },
          { name: 'CV Left Cam', icon: 'camera', status: 'online' },
          { name: 'CV Right Cam', icon: 'camera', status: 'online' },
          { name: 'Display', icon: 'monitor', status: 'online' },
          { name: 'App', icon: 'smartphone', status: 'offline' },
          { name: 'Tablets', icon: 'tablet', status: 'online' },
          { name: 'BM Tabs', icon: 'layout-grid', status: 'online' },
          { name: 'Server', icon: 'server', status: 'online' },
        ],
      },
    ],
  },
  {
    id: 'india',
    name: 'India Facility',
    flag: 'in',
    lanes: [
      {
        id: 1,
        name: 'Lane 1',
        type: 'Batting',
        devices: [
          { name: 'Bowling Machine', icon: 'zap', status: 'online' },
          { name: 'CV Left Cam', icon: 'camera', status: 'online' },
          { name: 'CV Right Cam', icon: 'camera', status: 'online' },
          { name: 'Display', icon: 'monitor', status: 'online' },
          { name: 'App', icon: 'smartphone', status: 'online' },
          { name: 'Tablets', icon: 'tablet', status: 'online' },
          { name: 'BM Tabs', icon: 'layout-grid', status: 'online' },
          { name: 'Server', icon: 'server', status: 'online' },
        ],
      },
      {
        id: 2,
        name: 'Lane 2',
        type: 'Batting',
        devices: [
          { name: 'Bowling Machine', icon: 'zap', status: 'online' },
          { name: 'CV Left Cam', icon: 'camera', status: 'online' },
          { name: 'CV Right Cam', icon: 'camera', status: 'online' },
          { name: 'Display', icon: 'monitor', status: 'online' },
          { name: 'App', icon: 'smartphone', status: 'online' },
          { name: 'Tablets', icon: 'tablet', status: 'warning' },
          { name: 'BM Tabs', icon: 'layout-grid', status: 'online' },
          { name: 'Server', icon: 'server', status: 'online' },
        ],
      },
      {
        id: 3,
        name: 'Lane 3',
        type: 'Batting',
        devices: [
          { name: 'Bowling Machine', icon: 'zap', status: 'online' },
          { name: 'CV Left Cam', icon: 'camera', status: 'online' },
          { name: 'CV Right Cam', icon: 'camera', status: 'offline' },
          { name: 'Display', icon: 'monitor', status: 'online' },
          { name: 'App', icon: 'smartphone', status: 'online' },
          { name: 'Tablets', icon: 'tablet', status: 'online' },
          { name: 'BM Tabs', icon: 'layout-grid', status: 'online' },
          { name: 'Server', icon: 'server', status: 'online' },
        ],
      },
      {
        id: 4,
        name: 'Lane 4',
        type: 'Batting',
        devices: [
          { name: 'Bowling Machine', icon: 'zap', status: 'online' },
          { name: 'CV Left Cam', icon: 'camera', status: 'online' },
          { name: 'CV Right Cam', icon: 'camera', status: 'online' },
          { name: 'Display', icon: 'monitor', status: 'online' },
          { name: 'App', icon: 'smartphone', status: 'online' },
          { name: 'Tablets', icon: 'tablet', status: 'online' },
          { name: 'BM Tabs', icon: 'layout-grid', status: 'online' },
          { name: 'Server', icon: 'server', status: 'online' },
        ],
      },
      {
        id: 5,
        name: 'Lane 5',
        type: 'Hybrid',
        devices: [
          { name: 'Bowling Machine', icon: 'zap', status: 'online' },
          { name: 'CV Left Cam', icon: 'camera', status: 'online' },
          { name: 'CV Right Cam', icon: 'camera', status: 'online' },
          { name: 'Display', icon: 'monitor', status: 'online' },
          { name: 'App', icon: 'smartphone', status: 'online' },
          { name: 'Tablets', icon: 'tablet', status: 'online' },
          { name: 'BM Tabs', icon: 'layout-grid', status: 'online' },
          { name: 'Server', icon: 'server', status: 'online' },
        ],
      },
      {
        id: 6,
        name: 'Lane 6',
        type: 'Hybrid',
        devices: [
          { name: 'Bowling Machine', icon: 'zap', status: 'online' },
          { name: 'CV Left Cam', icon: 'camera', status: 'online' },
          { name: 'CV Right Cam', icon: 'camera', status: 'online' },
          { name: 'Display', icon: 'monitor', status: 'online' },
          { name: 'App', icon: 'smartphone', status: 'online' },
          { name: 'Tablets', icon: 'tablet', status: 'online' },
          { name: 'BM Tabs', icon: 'layout-grid', status: 'online' },
          { name: 'Server', icon: 'server', status: 'online' },
        ],
      },
      {
        id: 7,
        name: 'Lane 7',
        type: 'Batting',
        devices: [
          { name: 'Bowling Machine', icon: 'zap', status: 'online' },
          { name: 'CV Left Cam', icon: 'camera', status: 'online' },
          { name: 'CV Right Cam', icon: 'camera', status: 'online' },
          { name: 'Display', icon: 'monitor', status: 'online' },
          { name: 'App', icon: 'smartphone', status: 'online' },
          { name: 'Tablets', icon: 'tablet', status: 'online' },
          { name: 'BM Tabs', icon: 'layout-grid', status: 'online' },
          { name: 'Server', icon: 'server', status: 'online' },
        ],
      },
    ],
  },
];
